### ISSUE TITLE
TAWoBA remastered issue

### ISSUE THREAD

**Issue by capitanjal** [minis-patchers/SynHelmsWithCirclets#1]
when this patcher is used with that mod it removes the circlet tag from some helmets that only have that tag it seems to be something to do that they are classified like light/heavy armor

**Comment by Michael-wigontherun** [comment]
It is this there is no filter for if it only has that one flag.

I fixed this in my fork of the patcher use https://github.com/Michael-wigontherun/SynHelmsWithCirclets in the Repository Path.

I submitted a pull request to [minis-patchers](https://github.com/minis-patchers) to merge it into the main page.

**Comment by Minizbot2012** [comment]
Fixed By merging #5
