### ISSUE TITLE
Invisible Circlets

### ISSUE THREAD

**Issue by Rhaevyn** [minis-patchers/SynHelmsWithCirclets#3]
I can't say for certain that it is this patcher causing it, but I am looking for the cause.  I use this patcher as well as KSHairsBaldHeadFixer, so it might be that one, or the fact I use both.  If someone could tell me how to find the culprit I'd appreciate it.  I have some nice circlets I'd like to actually see.

**Comment by Michael-wigontherun** [comment]
It is this there is no filter for if it only has that one flag.

I fixed this in my fork of the patcher use [https://github.com/Michael-wigontherun/SynHelmsWithCirclets](https://github.com/Michael-wigontherun/SynHelmsWithCirclets) in the Repository Path.

I submitted a pull request to [minis-patchers](https://github.com/minis-patchers) to merge it into the main page.

**Comment by Minizbot2012** [comment]
Should be fixed by merging #5
